### ISSUE TITLE
blank page after login with 0.5.x

### ISSUE THREAD

**Issue by djedje72** [anonaddy/docker#28] opened 2020-10-16 12:40 UTC
### Behaviour
Impossible to display website when logged.

#### Steps to reproduce this issue

1. install latest docker image (0.5.x)
2. register new account
3. verify email
4. try to login

#### Expected behaviour

> You should see Anonaddy page

#### Actual behaviour

> I can register and verify email. After that, after login, i got blank page, no error, javascript is successfully load but the app seems to not be initialized

**Comment by djedje72** [comment] 2020-10-16 13:02
Only the main page (aliases page) doesn't work. Others pages are OK.
![image](https://user-images.githubusercontent.com/18309946/96261291-8d147e00-0fc0-11eb-8765-6c7bda41b32c.png)

**Comment by willbrowningme** [comment] 2020-10-16 14:36
Thanks, that bug has been fixed in [v0.6.0](https://github.com/anonaddy/anonaddy/releases/tag/v0.6.0).

It was caused by an empty value being passed to Vue for the total fowarded, replied, blocked figures on the aliases page.

The query in the [ShowAliasController](https://github.com/anonaddy/anonaddy/blob/master/app/Http/Controllers/ShowAliasController.php) has been updated to `ifnull(sum(emails_forwarded),0)` to return 0 instead of null.

**Closed by willbrowningme** 2020-10-16 14:36 UTC

**Comment by crazy-max** [comment] 2020-10-16 15:35
@djedje72 @willbrowningme New image available (0.6.0)

**Comment by djedje72** [comment] 2020-10-21 07:53
thank you, alias page is OK in 0.6.0 😄
