### ISSUE TITLE
Error 500 on user login

### ISSUE THREAD

**Issue by luckydonald** [anonaddy/docker#272] opened 2024-04-04 02:14 UTC
I'm unable to login to my selfhosted instance. Emails are not redirected either.
v1.1.0

Don't know what could have changed. I'm seeing no log output on the php docker.

**Comment by luckydonald** [comment] 2024-04-04 14:14
Oh sorry @willbrowningme.
Thought it was a software issue at first.

Well, it was not.

**Comment by crazy-max** [comment] 2024-05-04 22:34
Your DB looks publicly exposed which is a bad practice? What's your compose configuration looks like? DB is not exposed in our examples: https://github.com/anonaddy/docker/blob/fd6c9fba9578499f7704047d628c59556d9dcbc7/examples/compose/compose.yml#L4-L18

**Comment by luckydonald** [comment] 2024-05-14 11:24
The compose file uses the provided example.

`.env` 
```.env
MYSQL_USER=luckydonald
MYSQL_PASSWORD=2346ljkdfjsdfgj32409#1215t24399DHKZ45z9bdß043tkldvsvbjn4btn-asdfag,sf342659023
```
All I added was a second phpmyadmin container.
I would log in with the user `luckydonald` and the secure password `2346ljkdfjsdfgj32409#1215t24399DHKZ45z9bdß043tkldvsvbjn4btn-asdfag,sf342659023` there.

**Comment by crazy-max** [comment] 2024-05-14 11:48
> All I added was a phpmyadmin container

Not sure if you don't share your compose file and we also don't have anything like this in our examples. If you expose your phpmyadmin instance publicly with the internal db exposed through it then it's probably why your db got hacked.

Closing as this is not reproducible with our exmaples.

**Closed as completed by crazy-max** 2024-05-14 11:48 UTC
Labels: status/needs-more-info

**Comment by luckydonald** [comment] 2024-05-14 11:58
I don't understand why you deliberately want the root user to have the very insecure password `""` without documenting that...

**Comment by luckydonald** [comment] 2024-05-14 12:00
>  then it's probably why your db got hacked.

It didn't got hacked, someone used the default password you set to `"root"` with the password <code>""</code> .

**Comment by crazy-max** [comment] 2024-05-15 21:35
> I don't understand why you deliberately want the root user to have the very insecure password `""` without documenting that...

What is provided in https://github.com/anonaddy/docker/tree/master/examples are just examples to have a anonaddy compose stack running. Up to anyone to tweak it based on their needs but setting root password in our examples is not needed.

**Comment by luckydonald** [comment] 2024-05-26 13:13
That's a good solution. Thanks.
