### ISSUE TITLE
Reply send from alias issue after upgrade to 0.10.0r1

### ISSUE THREAD

**Issue by strandundmeer** [anonaddy/docker#114] opened 2022-02-25 11:13 UTC
Good Morning,

I upgraded my instance to 0.10.0r1 and switched to rspamd, now I am unable to send / reply from an alias.
### Setup:
- Internal Mailserver running Mailcow, which is the only server who should be able to send / reply from an alias
- Anonaddy running in docker on a different host exclusively and worked before the switch to rspamd without issues.

### Problem:
After trying to send I do get an email telling me that I need to have a DMARC Policy in place which I do have

### Debugging:
Setting APP_DEBUG as well as POSTFIX_DEBUG to true is not telling my why the email is rejected.
I use split DNS and the internal DNS records should reflect all needed dmark, dkim, spf records as well as the external ones.

Doing a tcpdump for the dns resolution I do see that the MX record and the A records for my domain are requested and answered. But I do not see any query for the DMARC record or the DKIM key. 
Sending an email to an external address without having anonaddy in between, I see valid dmarc, dkim, spf in the header.

### Question:
- How can I find out why the emails are getting rejected? the email I do get is not very usefull.
- Is there a chance to just whitelist the internal server as trustworthy, I don't have the need for external servers to send replies?

Thanks for your help

**Comment by KevinRoebert** [comment] 2022-03-01 20:13
For me, the function is broken since version `0.10.0`. Have downgraded to `0.9.1` (`anonaddy/anonaddy:0.9.1`), there everything still works.

Attached is an error message.

<img width="582" alt="screen" src="https://user-images.githubusercontent.com/28713602/156241724-16866223-c465-497d-9d54-88ddfb516c60.png">

**Comment by strandundmeer** [comment] 2022-03-02 06:30
Thanks, I know that DKIM and DMARC are no longer supported.
Looking at my internal mail server i can verify that the email is dkim signed.
Looking at rspamd at anonaddy I don't see the header.
As I said before, I captured the traffic between Anonaddy and my DNS, I can see MX queries, queries to spamhouse, ... but no TXT queries for DMARC or DKIM...

**Comment by willbrowningme** [comment] 2022-03-07 08:39
Are you still having this issue on the latest release?

**Comment by crazy-max** [comment] 2022-08-01 11:22
Closing as this does not seem reproducible but feel free to re-open if you have the appropriate compose file, env file and logs to allow us to repro. Thanks.

**Closed by crazy-max** 2022-08-01 11:22 UTC
